name: Market Byte Bot (v2.3)

on:
  schedule:
    # (الجدول: 4 مرات يومياً - كل 6 ساعات)
    # (UTC: 5, 11, 17, 23)
    # (توقيت بغداد: 8ص, 2ظ, 8م, 2ص)
    - cron: '0 5,11,17,23 * * *'

  # هذا يسمح لنا بالاختبار اليدوي
  workflow_dispatch:

jobs:
  run-daily-poster:
    runs-on: ubuntu-latest
    env:
      # (المفاتيح القديمة)
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
      
      # (!!! المفاتيح الجديدة المطلوبة هنا v2.3 !!!)
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: pip install requests
        
      - name: Run Python Script
        run: python crypto_bot.py

