name: Market Byte Bot (v5.0 - Combined Logic)

on:
  schedule:
    # (v5.0) الجدول الزمني المدمج:
    
    # 1. للنشر اليومي (8 صباحاً بغداد)
    # (يعمل الساعة 5:00 UTC)
    - cron: '0 5 * * *'
    
    # 2. لفحص التنبيهات (كل 6 ساعات)
    # (يعمل الساعة 0, 6, 12, 18 UTC)
    - cron: '0 0,6,12,18 * * *'

  # (للاختبار اليدوي في أي وقت)
  workflow_dispatch:

jobs:
  run-smart-bot:
    runs-on: ubuntu-latest
    env:
      # (v5.0) المفاتيح الثلاثة المطلوبة
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
      COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      
      # (v5.0) هذا المتغير مهم ليعرف الكود إذا كان التشغيل "يدوياً"
      GITHUB_EVENT_NAME: ${{ github.event_name }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: pip install requests
        
      - name: Run Python Script (Smart Logic)
        run: python crypto_bot.py

