### الملف 2: "المُشغّل التلقائي" (المنبه)

هذا هو أهم ملف. إنه "المنبه" (Scheduler) الذي سيقوم بتشغيل البوت **4 مرات يومياً** (8 صباحاً، 2 ظهراً، 8 مساءً، 2 ليلاً بتوقيت بغداد).

* **المكان (هام جداً):** `.github/workflows/market_byte.yml`
    * (يجب أن تنشئ مجلداً اسمه `.github`، وبداخله مجلد `workflows`، ثم تضع هذا الملف بداخله).
* **المحتوى (انسخ هذا):**

```yaml:ملف التشغيل (v1.0 - بوت العملات):.github/workflows/market_byte.yml
# =============================================================================
#           *** ملف التشغيل التلقائي (v1.0 - Market Byte) ***
#
#  (ينشر 4 مرات يومياً - كل 6 ساعات)
# =============================================================================

name: Market Byte Bot (v1.0)

on:
  schedule:
    # (الجدول: 4 مرات يومياً - كل 6 ساعات)
    # (UTC: 5, 11, 17, 23)
    # (توقيت بغداد: 8ص, 2ظ, 8م, 2ص)
    - cron: '0 5,11,17,23 * * *'

  # هذا يسمح لنا بالاختبار اليدوي
  workflow_dispatch:

jobs:
  run-daily-poster:
    runs-on: ubuntu-latest
    env:
      # (المفاتيح السرية التي أضفتها للمستودع الجديد)
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
      # (لا نحتاج مفتاح API للعملات لهذا الكود)
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: pip install requests
        
      - name: Run Python Script
        run: python crypto_bot.py
```eof
